### ISSUE TITLE
Tax percentage not working

### ISSUE THREAD

**Issue by geoffreyvd** [concept-core/Invoiced#1]
The tax field only accepts true or false, while the API says it can be a "%" aswell -https://github.com/Invoiced/invoice-generator-api#invoice-fields 

`"fields[tax]" => "%"`
returns: The Fields[tax] field may only contain a true or false value

**Comment by concept-core** [comment]
This is because of the the validation of that field in my script.
It is either true or false because back when I made this I only needed it to be active or not.

**Comment by geoffreyvd** [comment]
I see, so I could simply bypass the validation for it to work

**Comment by concept-core** [comment]
yes you can even take it out of there if you want.
Or make some custom validation.
