### ISSUE TITLE
Tax object transforms decimal input to integer output

### ISSUE THREAD

**Issue by geoffreyvd** [concept-core/Invoiced#2]
The following code would output 8:
`"tax"=> 8.5,`

While I expect it to be 8,5

**Comment by concept-core** [comment]
I will need to fix this, not really sure if I want to now since I plan to rebuild this with slim.

**Comment by geoffreyvd** [comment]
Thanks for the answer, awesome response time!
What is the main reason to rebuild this, if I may ask

**Comment by concept-core** [comment]
because it mostly is just shit, 
I made this a long time ago when I just needed this and tried something out.

**Comment by geoffreyvd** [comment]
I see, it works fine for me, except for the 2 issues, thanks for the quick replys anyway!

**Comment by concept-core** [comment]
Your welcome did not expect somebody to use it tbh.

**Comment by geoffreyvd** [comment]
Yeah it is referenced on this page: https://github.com/Invoiced/invoice-generator-api , thought this was the official php implementations, apperently you're affiliated at all

**Comment by concept-core** [comment]
hmm ok, means I will need to rebuild this in time before more people will use it.
